name: KVIB Package Publish

on:
  # push:
  #   branches:
  #     - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag_version_output: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          # Defaults to the user or organization that owns the workflow file
          scope: '@kartverket' 
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ github.token }}

  publish-react-package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      
      - name: Bump react-components package.json
        run: npm version ${{ needs.build.outputs.tag_version_output }} --no-git-tag-version
        working-directory: static/js/react-components   
      
      - name: Publish react-components package on NPM
        run: npm publish --access public
        working-directory: static/js/react-components
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}


  publish-css-package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      
      - name: Bump CSS package.json
        run: npm version ${{ needs.build.outputs.tag_version_output }} --no-git-tag-version
        working-directory: static/css    
      
      - name: Publish CSS package on NPM
        run: npm publish --access public
        working-directory: static/css
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

